# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - lint
  - test
  - build
  - publish

## Project configuration
###

variables:
  PACKAGE_VERSION: "1.3.1"
  PACKAGE_NAME: discord_role_sync

## SAST -- default linter
###

sast:
  stage: lint

include:
  - template: Security/SAST.gitlab-ci.yml

## Main CI -- maven tests and packaging/publishing
###

maven-test:
  stage: test

  image: maven:3-eclipse-temurin-22
  script:
    - mvn test -Dpackage_version=${PACKAGE_VERSION}

  artifacts:
    expire_in: 30 days
    paths:
      - target/surefire-reports/
    reports:
      junit: target/surefire-reports/*.xml

maven-package:
  stage: build

  image: maven:3-eclipse-temurin-22
  script:
    - mvn package -Dpackage_version=${PACKAGE_VERSION}

  artifacts:
    expire_in: 30 days
    paths:
      - target/

publish-package:
  stage: publish

  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      curl \
        --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
        --upload-file target/${PACKAGE_NAME}-${PACKAGE_VERSION}.jar \
        ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PACKAGE_NAME}/${PACKAGE_VERSION}/${PACKAGE_NAME}-${PACKAGE_VERSION}.jar

## Python infra tests
###
python-infra-test:
  stage: test

  image: python:3.12-alpine
  before_script:
    - cd spigot_page
    - pip install -r requirements.txt
  script:
    - pytest --junitxml=report.xml
  artifacts:
    expire_in: 30 days
    paths:
      - spigot_page/report.xml
    reports:
      junit: spigot_page/report.xml

## Generate Spigot page description
###

generate-spigot-description:
  stage: build

  image: python:3.12-alpine
  before_script:
    - cd spigot_page
    - pip install -r requirements.txt
  script:
    - python markdown_to_bbcode.py ../README.md --out ./spigot_page.bb
  artifacts:
    expire_in: 30 days
    paths:
      - spigot_page/spigot_page.bb