name: DiscordRoleSync
version: "%package_version%"
author: Nicho
description: Sync Discord roles with the server's whitelist and permission plugins.
main: dev.nicho.rolesync.RoleSync

# Set API version to 1.13 to make it stop showing a warning when loading in later versions.
# This plugin has been tested in 1.8.8-1.21 and is confirmed working, though.
api-version: 1.13

softdepend:
  # This plugin can read from PlaceholderAPI in some strings, and provides
  # its own placeholders too.
  - PlaceholderAPI

depend:
  # Uses Vault to manage permissions
  - Vault

commands:
  discordrolesync:
    description: Commands to manage the DiscordRoleSync plugin.
    aliases:
      - drs
