name: DiscordRoleSync
version: 1.0.0-BETA.14
author: Nicho
description: Sync Discord roles with the server's whitelist and permission plugins.
main: dev.nicho.rolesync.RoleSync
depend:
  - Vault
loadbefore: # Minecord uses an older API version. The methods from their version have been deprecated but not removed.
  - Minecord
commands:
  discordrolesync:
    description: Commands to manage the DiscordRoleSync plugin.
    aliases:
      - drs
